### PR TITLE
word typo fix

### PR DESCRIPTION
**Pull request by alisonjo315**
Issue #29

### CODE REVIEW

**Comment by alisonjo315** [comment]
(If you think this is a good PR, it would be cool if you could add the `hacktoberfest-accepted` label -- if you're willing!  Totally understand if you'd rather not, I submit PRs like this any time of the year 😁 Either way, thank you for an awesome plugin!)

**Comment by Ultra-Instinct-05** [comment]
I am, in general, not in favor of Hactoberfest, as it has an infamous reputation for spam PR's, but this PR is fine in my book. I don't mind adding labels on genuine PR's (do note that I have not submitted any of my repos for the fest, if thats a thing in hactoberfest)

**Review by Ultra-Instinct-05 — COMMENTED** [review]
The spelling is wrong. Should be `Similarly`

**Comment by alisonjo315** [comment]
(Fair enough - thank you!)

Omg that's embarrassing 🤦‍♀️  Fixed.

**Comment by Ultra-Instinct-05** [comment]
Thank you !

**Pull request merged**
