### PR TITLE
Refactor Syntax

### LINKED ISSUE #33: Work better with Tailwind classes and custom values
### Description of your enhancement/feature request proposal.

Hi, example of some Tailwind markup for which this plugin could be enhanced:

`<div class="text-[#000AAA]">Lorem</div>`

When typing `text-[#`, the Twig package autocompletes with curly brackets so it becomes `text-[#{}`, but this is obviously the wrong behavior. If the Package could understand this it would be great.

### Alternatives.

Currently I'm manually fixing this erroneous autocompletes.

### PR DESCRIPTION
**Pull request by deathaxe**
Resolves #33

This PR...

1. introduces common `meta.template.twig` applied scope accross Text/HTML/JS/CSS
2. adjusts snippet selectors
3. adds some helper key bindings
4. applies syntax specific toggle comment rules to apply Twig comments by default but retain original syntax's block comment as variant 2.
5. renames contexts to use hyphens as subword-separators
6. reorders contexts following lessons learned from Go, Jinja and other template syntaxes
7. apply `meta.embedded` to tags and `source.twig` to their content.
8. fix various smaller highlighting bugs
9. merges html specific rules into twig indentation rules

Note: This PR requires ST4152+, most likely due to CSS.

To support older releases we'd need to vendor CSS.

### CODE REVIEW

**Comment by willrowe** [comment]
This looks great, I pulled down the branch, did some cursory testing, and it appears to fix a lot of the issues I was seeing. Thanks for putting in all the work to update the syntax @deathaxe!

**Comment by deathaxe** [comment]
Feel free to post any issues you encounter.

**Comment by willrowe** [comment]
1. When adding curly braces `{{}}` inside of quotes like `"{{}}"`, it doesn't add spaces like it does when not inside quotes: `{{  }}`.
2. When pressing return in between an opening and closing statements it does not insert a new line and indent as expected.

**Comment by willrowe** [comment]
I just pulled down the latest commits and both the issues I found are working now.

**Comment by deathaxe** [comment]
@braver: I think this PR is ready for release.

Required channel changes are prepared at https://github.com/wbond/package_control_channel/pull/8995

With a look at amount of changes it's probably worth a new major version.

**Comment by braver** [comment]
Looks good! I'll be using it on and off the coming days, perhaps I'll run into something, but this looks really solid. Let's 🚀

**Pull request merged**
